import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

export function generateCompatibilityEntries(root, { clean = false } = {}) {
  root = resolve(root);
  const dist = join(root, "dist");
  const manifestFile = join(root, ".compatibility-entries.json");
  const previous = existsSync(manifestFile)
    ? JSON.parse(readFileSync(manifestFile, "utf8")).files
    : [];
  const hash = (content) => createHash("sha256").update(content).digest("hex");
  const previousByPath = new Map(previous.map((file) => [file.path, file]));
  const generated = new Map();
  const marker =
    "// Generated by scripts/generateCompatibilityEntries.mjs. Do not edit.\n";

  function outputPath(path) {
    const absolute = resolve(root, path);
    const normalized = relative(root, absolute).split(sep).join("/");
    if (
      path !== normalized ||
      !absolute.startsWith(root + sep) ||
      normalized.startsWith("dist/") ||
      normalized.startsWith("src/") ||
      !/^(?:[A-Z][^/]*\/|utilities\/|visualization\/|examples\/|styles\/|types\.d\.ts$|style\.css$)/.test(
        normalized,
      )
    )
      throw new Error("Invalid compatibility output path: " + path);
    return absolute;
  }

  function verifyOwned(file) {
    const output = outputPath(file.path);
    if (existsSync(output) && hash(readFileSync(output)) !== file.sha256)
      throw new Error(
        "Refusing to overwrite modified compatibility file: " + output,
      );
  }

  function* walk(folder) {
    for (const entry of readdirSync(folder, { withFileTypes: true })) {
      const path = join(folder, entry.name);
      if (entry.isDirectory()) yield* walk(path);
      else if (entry.isFile()) yield path;
    }
  }

  function exportShape(path) {
    const source = ts.createSourceFile(
      path,
      readFileSync(path, "utf8"),
      ts.ScriptTarget.Latest,
      true,
    );
    let defaultExport = false;
    let exportEquals = false;
    for (const statement of source.statements) {
      if (ts.isExportAssignment(statement)) {
        if (statement.isExportEquals) exportEquals = true;
        else defaultExport = true;
      }
      if (
        statement.modifiers?.some(
          (modifier) => modifier.kind === ts.SyntaxKind.DefaultKeyword,
        )
      )
        defaultExport = true;
      if (
        ts.isExportDeclaration(statement) &&
        statement.exportClause &&
        ts.isNamedExports(statement.exportClause)
      )
        defaultExport ||= statement.exportClause.elements.some(
          (element) => element.name.text === "default",
        );
    }
    return { defaultExport, exportEquals };
  }

  function add(path, content, source, kind, defaultExport = false) {
    outputPath(path);
    generated.set(path, {
      content,
      path,
      source,
      kind,
      defaultExport,
      sha256: hash(content),
    });
  }

  function forward(path, kind) {
    const source = join(dist, path);
    const shape = exportShape(source);
    const targetPath =
      kind === "declaration" ? source.replace(/\.d\.ts$/, ".js") : source;
    let target = relative(dirname(join(root, path)), targetPath)
      .split(sep)
      .join("/");
    if (!target.startsWith(".")) target = "./" + target;
    const specifier = JSON.stringify(target);
    const contents =
      kind === "commonjs"
        ? `module.exports = require(${specifier});\n`
        : shape.exportEquals
          ? `import entry = require(${specifier});\nexport = entry;\n`
          : `export * from ${specifier};\n${shape.defaultExport ? `export { default } from ${specifier};\n` : ""}`;
    add(path, marker + contents, "dist/" + path, kind, shape.defaultExport);
  }

  if (!clean) {
    // TypeScript emits declarations for .ts files but does not copy authored .d.ts.
    const sourceRoot = join(root, "src");
    if (existsSync(sourceRoot)) {
      for (const source of walk(sourceRoot)) {
        if (!source.endsWith(".d.ts")) continue;
        const target = join(dist, relative(sourceRoot, source));
        mkdirSync(dirname(target), { recursive: true });
        writeFileSync(target, readFileSync(source));
      }
    }
    for (const source of walk(dist)) {
      const path = relative(dist, source).split(sep).join("/");
      if (path.endsWith(".d.ts")) forward(path, "declaration");
      else if (/^(?:[^/]+\/index|utilities\/[^/]+)\.mjs$/.test(path))
        forward(path, "module");
      else if (/^(?:[^/]+\/index|utilities\/[^/]+)\.js$/.test(path))
        forward(path, "commonjs");
      else if (path === "style.css" || /^styles\/[^/]+\.scss$/.test(path))
        add(path, readFileSync(source), "dist/" + path, "style");
    }
    if (!generated.has("types.d.ts") || !generated.has("style.css"))
      throw new Error(
        "Build both JavaScript and declarations before generating compatibility entries.",
      );
  }

  // Only remove or overwrite files recorded by the previous generation whose
  // contents still match. Never remove a directory or replace an unowned file.
  for (const file of previous) verifyOwned(file);
  for (const file of generated.values()) {
    if (existsSync(outputPath(file.path)) && !previousByPath.has(file.path))
      throw new Error(
        "Refusing to overwrite unowned compatibility file: " + file.path,
      );
  }
  for (const file of previous) {
    if (!generated.has(file.path) && existsSync(outputPath(file.path)))
      unlinkSync(outputPath(file.path));
  }
  for (const file of generated.values()) {
    const output = outputPath(file.path);
    mkdirSync(dirname(output), { recursive: true });
    writeFileSync(output, file.content);
  }
  if (clean) {
    if (existsSync(manifestFile)) unlinkSync(manifestFile);
  } else {
    const files = [...generated.values()].map(
      ({ path, source, kind, defaultExport, sha256 }) => ({
        path,
        source,
        kind,
        defaultExport,
        sha256,
      }),
    );
    writeFileSync(
      manifestFile,
      JSON.stringify({ version: 1, files }, null, 2) + "\n",
    );
    console.log(`Generated ${files.length} package-root compatibility files.`);
  }
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  generateCompatibilityEntries(
    resolve(dirname(fileURLToPath(import.meta.url)), "../easy-ui-react"),
    { clean: process.argv.includes("--clean") },
  );
}
